import json
import logging
import sys
import argparse
from pathlib import Path
from typing import Dict, List, Any, Set

# --- SRE Configuration: Professional Logging ---
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] nit-fabric.visualizer: %(message)s",
    stream=sys.stderr
)
logger = logging.getLogger("nit-fabric.visualizer")

class NetworkVisualizer:
    """
    Generates a Mermaid.js network topology from a discovery context.
    """
    def __init__(self, context_path: str = "context.json"):
        self.context_path = context_path
        self.nodes: Set[str] = set()
        self.edges: List[str] = []
        self.subgraphs: Dict[str, List[str]] = {"AWS": [], "GCP": []}
        
        self.context = self._load_context()

    def _load_context(self) -> Dict[str, Any]:
        if not Path(self.context_path).exists():
            logger.warning(f"Context file {self.context_path} not found. Using empty context.")
            return {}
        with open(self.context_path, "r") as f:
            return json.load(f)

    def _add_node(self, platform: str, name: str, node_type: str = "round") -> str:
        # Sanitize for Mermaid IDs
        node_id = f"{platform}_{name}".replace("-", "_").replace(" ", "_")
        label = f"\"{name}\""
        
        if node_type == "round":
            self.nodes.add(f"    {node_id}({label})")
        elif node_type == "database":
            self.nodes.add(f"    {node_id}[({label})]")
        else:
            self.nodes.add(f"    {node_id}[{label}]")
            
        if platform in self.subgraphs:
            self.subgraphs[platform].append(node_id)
        return node_id

    def build_topology(self):
        """Dynamically builds graph nodes from discovered resources"""
        logger.info("Building topology from context...")
        
        # 1. AWS Resources
        for vpc in self.context.get("vpcs", []):
            vpc_node = self._add_node("AWS", f"VPC: {vpc.get('id')}")
            for ep in vpc.get("endpoints", []):
                svc_name = ep.get("Service", "Unknown")
                ep_node = self._add_node("AWS", f"Endpoint: {svc_name}")
                self.edges.append(f"{vpc_node} -- \"PrivateLink\" --> {ep_node}")

        for s3 in self.context.get("aws_s3_buckets", []):
            s3_node = self._add_node("AWS", s3.get("name"), node_type="database")

        # 2. GCP Resources
        for cluster in self.context.get("gke_clusters", []):
            c_node = self._add_node("GCP", f"GKE: {cluster.get('name')}")
            for np in cluster.get("node_pools", []):
                np_node = self._add_node("GCP", f"Pool: {np}")
                self.edges.append(f"{c_node} --- {np_node}")

        for instance in self.context.get("gcp_instances", []):
            self._add_node("GCP", f"VM: {instance.get('name')}")

    def emit_mermaid(self) -> str:
        lines = ["graph TD", "  %% Generated by nit-fabric visualizer"]
        
        for platform, members in self.subgraphs.items():
            if members:
                lines.append(f"  subgraph {platform}")
                # We only want nodes that belong to this platform
                for node in self.nodes:
                    node_id = node.strip().split("(" if "(" in node else "[")[0]
                    if node_id in members:
                        lines.append(node)
                lines.append("  end")

        for edge in self.edges:
            lines.append(f"  {edge}")
            
        return "\n".join(lines)

    def write_report(self, output_path: str):
        mermaid_code = self.emit_mermaid()
        with open(output_path, "w") as f:
            f.write("# Network Topology Report\n\n")
            f.write("```mermaid\n")
            f.write(mermaid_code + "\n")
            f.write("```\n")
        logger.info(f"Report successfully written to {output_path}")

def main():
    parser = argparse.ArgumentParser(description="nit-fabric Visualizer")
    
    # Default paths
    base_out = Path(__file__).parent.parent.parent / "out"
    default_context = base_out / "context.json"
    default_output = base_out / "network_state.md"
    
    parser.add_argument("--context", default=str(default_context), help="Path to context file")
    parser.add_argument("--output", default=str(default_output), help="Path to output markdown")
    args = parser.parse_args()

    # Ensure output directory exists
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)

    visualizer = NetworkVisualizer(context_path=args.context)
    visualizer.build_topology()
    visualizer.write_report(args.output)

if __name__ == "__main__":
    main()
